version: '3'

services:
    web:
        image: "levilol/nginx:${TAG}"
        deploy:
            replicas: 2
            restart_policy:
              condition: on-failure
        networks:
            - webnet
        depends_on:
          - app
    app:
        image: "levilol/lol_app:${TAG}"
        deploy:
            replicas: 10
            restart_policy:
              condition: on-failure
        networks:
            - webnet
    lb:
        image: "levilol/haproxy:${TAG}"
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        ports:
            - "80:80"
            - "443:443"
            - "70:70"
        networks:
            - webnet
        depends_on:
          - web
networks:
    webnet:
